### ISSUE TITLE
Relation with CGUs-versions and CGUs-snapshots?

### ISSUE THREAD

**Issue by michielbdejong** [ambanum/CGUs-data#4]
It seems that since 5 days this repo no longer receives updates, but instead:
* `sanitized/` was moved to https://github.com/ambanum/CGUs-versions
* `raw/` was moved to  https://github.com/ambanum/CGUs-snapshots
Right?

**Comment by Ndpnt** [comment]
Yes, that's exactly right.
We will archive this repo to avoid confusion.

**Comment by michielbdejong** [comment]
Thanks!
